spring:
  application:
    name: personal-budget-service
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/personal_budget?useSSL=false&serverTimezone=UTC
      username: pf-personal-budget-command
      password: pf-personal-budget-command
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 9091

